import { audit } from "@/lib/audit";
import { requirePermission, requireUser } from "@/lib/auth";
import { getEnv } from "@/lib/cloudflare";
import { ValidationError, withErrorHandling } from "@/lib/errors";
import { jsonBody, optionalString, requiredString } from "@/lib/http";
import { processScan } from "@/lib/services/assetService";
import type { ScanMode } from "@/lib/types";
const modes = new Set<ScanMode>(["receive","stage","unstage","load","unload","deliver","pickup","warehouse_return","clean_start","clean_complete","inspect","audit","quarantine","repair","retire","mark_missing","recover"]);
export const POST = withErrorHandling(async (request) => { const ctx = await requireUser(request); requirePermission(ctx, "scans.create"); const body = await jsonBody<{ idempotencyKey?: unknown; assetIdentifier?: unknown; mode?: unknown; orderId?: unknown; assignmentId?: unknown; vehicleId?: unknown; notes?: unknown; outcome?: unknown; condition?: unknown }>(request); if (typeof body.mode !== "string" || !modes.has(body.mode as ScanMode)) throw new ValidationError("A valid scan mode is required"); const env = await getEnv(); const result = await processScan(env.DB, { idempotencyKey: requiredString(body.idempotencyKey, "idempotencyKey", 200), assetIdentifier: requiredString(body.assetIdentifier, "assetIdentifier", 200), mode: body.mode as ScanMode, orderId: optionalString(body.orderId, "orderId", 100), assignmentId: optionalString(body.assignmentId, "assignmentId", 100), vehicleId: optionalString(body.vehicleId, "vehicleId", 100), notes: optionalString(body.notes, "notes", 4000), outcome: optionalString(body.outcome, "outcome", 30), condition: optionalString(body.condition, "condition", 100), userId: ctx.user.id, deviceId: request.headers.get("x-device-id"), deviceTimestamp: new Date().toISOString() }); await audit(env.DB, { actorUserId: ctx.user.id, action: "asset.scanned", entityType: "asset", entityId: result.assetId ?? null, detail: { mode: body.mode, result }, ip: ctx.ip }); return Response.json(result, { status: result.ok ? 200 : 409 }); });
