import { audit } from "@/lib/audit";
import { requirePermission, requireUser } from "@/lib/auth";
import { getEnv } from "@/lib/cloudflare";
import { id, nowIso, q, run } from "@/lib/db";
import { ValidationError, withErrorHandling } from "@/lib/errors";
import { jsonBody, optionalString, requiredString } from "@/lib/http";
import { nextDocumentNumber } from "@/lib/numbering";
export const GET = withErrorHandling(async request => { const ctx = await requireUser(request); requirePermission(ctx, "assignments.view", "dispatch.view"); const env = await getEnv(); const date = new URL(request.url).searchParams.get("date") ?? new Date().toISOString().slice(0, 10); const assignments = await q(env.DB, "SELECT a.*, o.order_number, COALESCE(c.business_name, trim(COALESCE(c.first_name,'') || ' ' || COALESCE(c.last_name,''))) AS customer_name FROM assignments a LEFT JOIN orders o ON o.id=a.order_id LEFT JOIN customers c ON c.id=o.customer_id WHERE a.scheduled_date = ? ORDER BY a.window_start, a.priority", date); return Response.json({ date, assignments }); });
export const POST = withErrorHandling(async request => { const ctx = await requireUser(request); requirePermission(ctx, "assignments.manage", "dispatch.manage"); const body = await jsonBody<{ type?: unknown; orderId?: unknown; scheduledDate?: unknown; windowStart?: unknown; windowEnd?: unknown; priority?: unknown }>(request); const type = requiredString(body.type, "type", 50); if (!new Set(["delivery","pickup","swap","redelivery","warehouse_task"]).has(type)) throw new ValidationError("Unsupported assignment type"); const scheduledDate = requiredString(body.scheduledDate, "scheduledDate", 10); const priority = body.priority == null ? 2 : Number(body.priority); if (![1,2,3].includes(priority)) throw new ValidationError("priority must be 1, 2, or 3"); const env = await getEnv(), assignmentId = id("asn"), number = await nextDocumentNumber(env.DB, "assignment"); await run(env.DB, "INSERT INTO assignments (id, assignment_number, assignment_type, order_id, scheduled_date, window_start, window_end, priority, status, created_by, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, 'scheduled', ?, ?, ?)", assignmentId, number, type, optionalString(body.orderId, "orderId", 100), scheduledDate, optionalString(body.windowStart, "windowStart", 10), optionalString(body.windowEnd, "windowEnd", 10), priority, ctx.user.id, nowIso(), nowIso()); await audit(env.DB, { actorUserId: ctx.user.id, action: "assignment.created", entityType: "assignment", entityId: assignmentId, detail: { assignmentNumber: number, type }, ip: ctx.ip }); return Response.json({ id: assignmentId, assignmentNumber: number }, { status: 201 }); });
