"use client";
import { ReactNode, useEffect, useState } from "react";

type Dashboard = { date: string; metrics: { stops: number; totesInField: number; agreementsAwaiting: number; openBalanceCents: number }; assignments: { id: string; assignment_number: string; assignment_type: string; scheduled_date: string; window_start: string | null; status: string; order_number: string | null; customer_name: string | null }[] };
const money = (cents: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(cents / 100);
const links = [["▦", "Dashboard", "/ops"], ["◌", "Inquiries", "/inquiries"], ["♙", "Customers", "/customers"], ["☷", "Order desk", "/orders"], ["➜", "Dispatch", "/dispatch"], ["$", "Billing", "/billing"], ["▣", "Inventory", "/inventory"]] as const;

function Shell({ children }: { children: ReactNode }) { const [user, setUser] = useState<{ name: string; email: string } | null>(null); const path = typeof window === "undefined" ? "" : window.location.pathname; useEffect(() => { fetch("/api/auth/me").then(async r => { if (!r.ok) { location.assign("/login"); return; } setUser((await r.json() as { user: { name: string; email: string } }).user); }); }, []); return <div className="kimi-ops"><aside><a className="kimi-brand" href="/ops"><img src="/brand/great-lakes-moving-totes.png" alt="Great Lakes Moving Totes" /><span>ToteOps<small>Operations dashboard</small></span></a><nav>{links.map(([icon,label,href]) => <a className={path === href ? "active" : ""} href={href} key={href}><b>{icon}</b>{label}</a>)}</nav><div className="kimi-user"><strong>{user?.name ?? "Loading…"}</strong><span>{user?.email}</span><button onClick={() => fetch("/api/auth/logout", { method: "POST" }).then(() => location.assign("/login"))}>Sign out</button></div></aside><section className="kimi-main"><header><button className="kimi-menu" onClick={() => document.querySelector(".kimi-ops")?.classList.toggle("menu-open")}>☰</button><h1>Operations dashboard</h1><a href="/site/">View marketing site →</a></header>{children}</section></div>; }

export function KimiOpsDashboard() { const [data, setData] = useState<Dashboard | null>(null), [error,setError]=useState(""); useEffect(() => { fetch("/api/dashboard").then(async r => { if (!r.ok) { setError("Unable to load operations data."); return; } setData(await r.json() as Dashboard); }); }, []); return <Shell>{!data ? <p className="kimi-loading">{error || "Loading ToteOps…"}</p> : <div className="kimi-content"><div className="kimi-kpis"><article><span>Active rentals</span><strong>{data.metrics.totesInField}</strong><i>▣</i></article><article><span>Stops today</span><strong>{data.metrics.stops}</strong><i>➜</i></article><article><span>Agreements waiting</span><strong>{data.metrics.agreementsAwaiting}</strong><i>◷</i></article><article><span>Open balance</span><strong>{money(data.metrics.openBalanceCents)}</strong><i>$</i></article></div><div className="kimi-grid"><section className="kimi-panel"><header><h2>Today’s dispatch</h2><a href="/dispatch">Open dispatch →</a></header>{data.assignments.length ? <ul>{data.assignments.map(a => <li key={a.id}><div><strong>{a.assignment_type.replaceAll("_"," ")} · {a.assignment_number}</strong><span>{a.order_number ? `${a.order_number} · ${a.customer_name}` : "Warehouse task"}</span></div><time>{a.window_start || "Unscheduled"}</time><em>{a.status}</em></li>)}</ul> : <p className="kimi-empty">No stops scheduled today.</p>}</section><section className="kimi-panel"><header><h2>Quick actions</h2></header><div className="kimi-actions"><a href="/orders">Create rental order</a><a href="/customers">Add customer</a><a href="/inventory">Receive equipment</a><a href="/billing">Create invoice</a></div></section></div></div>}</Shell>; }
