"use client";
import { useEffect, useState } from "react";
type Report = { range: { days: number; start: string; end: string }; metrics: Record<string, number>; assets: { status: string; count: number }[]; daily: { day: string; orders: number; billed: number; collected: number }[] };
const money = (value: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(value / 100);
const words = (value: string) => value.replaceAll("_", " ");
export function ReportsDesk() {
  const [days, setDays] = useState(30), [report, setReport] = useState<Report | null>(null), [error, setError] = useState("");
  useEffect(() => { fetch(`/api/reports?days=${days}`).then(async r => { if (!r.ok) { setError("Unable to load reports."); return; } setReport(await r.json() as Report); }).catch(() => setError("Unable to load reports.")); }, [days]);
  const m = report?.metrics;
  return <main className="desk reports-desk"><header className="desk-header"><div><p className="eyebrow">OPERATIONS REPORTING</p><h1>Performance overview</h1></div><select aria-label="Report period" value={days} onChange={e => setDays(Number(e.target.value))}><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="90">Last 90 days</option><option value="365">Last 12 months</option></select></header>{error && <p className="form-error">{error}</p>}{!report ? <p className="empty">Loading operations metrics…</p> : <><section className="report-kpis"><article><span>Orders created</span><strong>{m?.orders ?? 0}</strong><small>{money(m?.bookedCents ?? 0)} booked</small></article><article><span>Collected</span><strong>{money(m?.collectedCents ?? 0)}</strong><small>{money(m?.billedCents ?? 0)} invoiced</small></article><article><span>Open balance</span><strong>{money(m?.openBalanceCents ?? 0)}</strong><small>{m?.completed ?? 0} completed rentals</small></article><article><span>Cancellations</span><strong>{m?.cancellations ?? 0}</strong><small>{money(m?.refundsCents ?? 0)} refunded</small></article></section><section className="record-grid"><section><h2>Daily activity</h2><div className="report-table"><div className="report-head"><span>Date</span><span>Orders</span><span>Billed</span><span>Collected</span></div>{report.daily.length ? report.daily.map(row => <div className="report-row" key={row.day}><span>{new Date(`${row.day}T12:00:00`).toLocaleDateString()}</span><b>{row.orders}</b><b>{money(row.billed)}</b><b>{money(row.collected)}</b></div>) : <p className="empty">No activity in this period.</p>}</div></section><section><h2>Inventory by status</h2>{report.assets.map(asset => <div className="record-row" key={asset.status}><strong>{words(asset.status)}</strong><b>{asset.count}</b></div>)}</section></section></>}</main>;
}
