import { getEnv } from "@/lib/cloudflare";
import { id, nowIso, one, q, run } from "@/lib/db";

type Ctx = { params: Promise<{ endpoint: string[] }> };
const json = (body: unknown, status = 200) => Response.json(body, { status, headers: { "cache-control": "no-store", "x-content-type-options": "nosniff" } });
const error = (message: string, code = "INVALID_INPUT", status = 400) => json({ error: message, code }, status);
const cents = (amount: number) => Math.round(amount * 100);
const dollars = (amount: number) => Math.round(amount) / 100;
async function body(request: Request) { try { const value = await request.json(); return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : null; } catch { return null; } }
async function authorize(request: Request) { const env = await getEnv(); return !env.PUBLIC_API_KEY || request.headers.get("x-api-key") === env.PUBLIC_API_KEY; }
const zone = (row: { id: string; name: string; zone_fee_cents: number; active: number } | null) => row ? { id: row.id, name: row.name, fee: row.zone_fee_cents / 100, description: `${row.name} delivery area.`, active: !!row.active } : null;

export async function POST(request: Request, context: Ctx) {
  if (!await authorize(request)) return error("Unauthorized public API request", "UNAUTHORIZED", 401);
  const path = (await context.params).endpoint.join("/"); const input = await body(request); if (!input) return error("Request body must be a JSON object"); const env = await getEnv();
  if (path === "service-area/check") {
    const zip = typeof input.zip === "string" ? input.zip.trim() : "", cityName = typeof input.city === "string" ? input.city.trim() : "";
    if (!/^\d{5}$/.test(zip) || !cityName) return error("Enter a street, city, and valid ZIP code");
    const match = await one<{ id:string; name:string; zone_fee_cents:number; active:number; city_name:string; city_slug:string; zip:string; blurb:string; local_tips_json:string }>(env.DB, "SELECT z.id,z.name,z.zone_fee_cents,z.active,s.city_name,s.city_slug,s.zip,s.blurb,s.local_tips_json FROM service_zone_zips s JOIN service_zones z ON z.id=s.zone_id WHERE s.zip=? AND s.active=1 AND z.active=1", zip);
    if (!match || match.city_name.toLowerCase() !== cityName.toLowerCase()) { const z3 = await one<{id:string;name:string;zone_fee_cents:number;active:number}>(env.DB, "SELECT id,name,zone_fee_cents,active FROM service_zones WHERE name LIKE '%Zone 3%' AND active=1 LIMIT 1"); return json({ status:"custom-review", zone:zone(z3), city:null, message:"We’ll review this address for custom-route availability." }); }
    return json({ status:"in-zone", zone:zone(match), city:{ name:match.city_name, slug:match.city_slug, zoneId:match.id, zips:[match.zip], blurb:match.blurb, localTips:JSON.parse(match.local_tips_json || "[]") }, message:`${match.city_name} is inside our ${match.name}.` });
  }
  if (path === "availability/check") {
    const packageSlug = typeof input.packageSlug === "string" ? input.packageSlug : "", deliveryDate = typeof input.deliveryDate === "string" ? input.deliveryDate : "", pickupDate = typeof input.pickupDate === "string" ? input.pickupDate : "", deliveryZip = typeof input.deliveryZip === "string" ? input.deliveryZip : "";
    const packages = await q<{id:string;name:string}>(env.DB, "SELECT id,name FROM rental_packages WHERE active=1 AND is_custom=0 ORDER BY tote_quantity"); const slugs = packages.map(p => p.name.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,""));
    const area = await one<{id:string}>(env.DB, "SELECT s.id FROM service_zone_zips s JOIN service_zones z ON z.id=s.zone_id WHERE s.zip=? AND s.active=1 AND z.active=1", deliveryZip);
    const status = !area ? "outside-area" : (!deliveryDate || !pickupDate || pickupDate < deliveryDate) ? "date-adjustment" : "custom-review";
    await run(env.DB, "INSERT INTO availability_inquiries (id,package_slug,delivery_date,pickup_date,delivery_zip,result_status,created_at) VALUES (?,?,?,?,?,?,?)", id("avi"),packageSlug,deliveryDate||null,pickupDate||null,deliveryZip||null,status,nowIso());
    const copy: Record<string,[string,string]> = { "outside-area":["Outside standard service area","Request a custom quote and our team will review your route."], "date-adjustment":["Date adjustment needed","Choose valid delivery and pickup dates to continue."], "custom-review":["Availability review required","We’ll confirm equipment and route capacity before accepting a reservation."] };
    return json({ status, headline:copy[status][0], detail:copy[status][1], availablePackageSlugs:status === "outside-area" ? [] : slugs });
  }
  if (path === "pricing/quote") {
    const packageSlug = typeof input.packageSlug === "string" ? input.packageSlug : ""; const pkg = (await q<{id:string;name:string;launch_price_cents:number;standard_price_cents:number;effective_date:string;expiration_date:string|null;extra_week_price_cents:number}>(env.DB,"SELECT * FROM rental_packages WHERE active=1 AND is_custom=0")).find(p => p.name.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"") === packageSlug); if (!pkg) return error("Package is unavailable", "PACKAGE_UNAVAILABLE", 404);
    const z = typeof input.zoneId === "string" ? await one<{id:string;name:string;zone_fee_cents:number}>(env.DB,"SELECT id,name,zone_fee_cents FROM service_zones WHERE id=? AND active=1",input.zoneId) : null; const base = (pkg.effective_date <= new Date().toISOString().slice(0,10) && (!pkg.expiration_date || pkg.expiration_date >= new Date().toISOString().slice(0,10))) ? pkg.launch_price_cents : pkg.standard_price_cents; let subtotal=base; const lines=[{label:`${pkg.name} package`,amount:base/100}]; const promo=typeof input.promoCode === "string" ? await one<{id:string;discount_type:string;discount_value:number}>(env.DB,"SELECT id,discount_type,discount_value FROM promotional_codes WHERE code=? AND active=1 AND (starts_at IS NULL OR starts_at<=?) AND (ends_at IS NULL OR ends_at>=?)",input.promoCode.trim().toUpperCase(),nowIso(),nowIso()) : null; const discount=promo ? (promo.discount_type === "percent" ? Math.round(subtotal*promo.discount_value/100) : promo.discount_value) : 0; const zoneFee=z?.zone_fee_cents??0, tax=Math.round((subtotal+zoneFee-discount)*.06), total=subtotal+zoneFee-discount+tax, quoteId=id("pqt"); await run(env.DB,"INSERT INTO public_quote_snapshots (id,package_id,zone_id,promo_code_id,subtotal_cents,zone_fee_cents,discount_cents,tax_cents,total_cents,snapshot_json,expires_at,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)",quoteId,pkg.id,z?.id??null,promo?.id??null,subtotal,zoneFee,discount,tax,total,JSON.stringify({lines}),new Date(Date.now()+86400000).toISOString(),nowIso()); if(z&&zoneFee)lines.push({label:`${z.name} delivery fee`,amount:zoneFee/100}); if(discount)lines.push({label:"Promotion",amount:-discount/100}); return json({lines,subtotal:dollars(subtotal),zoneFee:dollars(zoneFee),discount:dollars(discount),estimatedTax:dollars(tax),estimatedTotal:dollars(total),quoteId});
  }
  if (path === "leads" || path === "reservations") { const type=path === "reservations" ? "reservation" : typeof input.type === "string" ? input.type : ""; if (!new Set(["contact","business-account","custom-quote","outside-area","referral","order-support","reservation"]).has(type)) return error("Unsupported submission type"); const reference=`${type === "reservation" ? "GLT" : "LEAD"}-${crypto.randomUUID().replace(/-/g,"").slice(0,6).toUpperCase()}`; const now=nowIso(); await run(env.DB,"INSERT INTO public_leads (id,reference,lead_type,pipeline_status,payload_json,consent,source_page,ip_hash,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?)",id("lead"),reference,type,type === "business-account" ? "business-account-review" : "new",JSON.stringify(input),input.consent === true ? 1 : 0,typeof input.sourcePage === "string" ? input.sourcePage : null,null,now,now); return json({ok:true,reference,message:type === "reservation" ? "Reservation request received for review." : "Thanks — we received your request."},201); }
  return error("Unknown public endpoint","NOT_FOUND",404);
}
